# Generated by Django 4.2.4 on 2023-08-20 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inativado', models.BooleanField(default=False)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('inativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inativado', models.BooleanField(default=False)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('inativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inativado', models.BooleanField(default=False)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('inativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inativado', models.BooleanField(default=False)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoriacomputador')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('inativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.localizacao')),
                ('usuario_atualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inativado', models.BooleanField(default=False)),
                ('inativado_em', models.DateTimeField(blank=True, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('senha', models.CharField(max_length=10)),
                ('horario_entrada', models.DateTimeField(auto_now_add=True)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], max_length=20)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.computador')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fila')),
                ('inativado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('usuario_atualizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
            },
        ),
    ]
