# Generated by Django 4.2.4 on 2023-08-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacomputador',
            options={'verbose_name_plural': 'Categoria de computadores'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name_plural': 'Localizações'},
        ),
        migrations.AddField(
            model_name='categoriacomputador',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
    ]
